-- Supabase owns sign-in, so anyone may create an identity there. This is the
-- column that decides whether having one lets you into the register.
--
--   ALTER TABLE "users" ADD COLUMN "pendingApproval" boolean DEFAULT false NOT NULL;
--
-- Defaults to false, so every existing account keeps working exactly as before
-- and no administrator is signed out by this. Only rows created by the sign-in
-- path set it.
--
-- Separate from "isActive" rather than reusing it, because the two mean opposite
-- things to the person locked out: pending is "not approved yet", which is
-- routine and cleared by one click, and deactivated is "your access was
-- withdrawn". Collapsing them would make the message sent to a suspended officer
-- indistinguishable from the one sent to somebody who signed up this morning.
--
-- Not an enum and not nullable: the three states that matter are pending, active
-- and deactivated, which is two booleans and no more, and a NOT NULL default
-- means a row cannot exist in an unstated fourth state.
ALTER TABLE "users" ADD COLUMN "pendingApproval" boolean DEFAULT false NOT NULL;
