// Concatenate drizzle/*.sql into one script the Supabase SQL Editor can run.
//
// Why this exists: `pnpm db:push` and the db-push workflow both need a
// PostgreSQL connection that verifies Supabase's own CA certificate, which means
// fetching a CA certificate from the dashboard first. That is the right path and
// it is what CI does, but it is a manual step standing between an operator and
// an empty database — and the failure it produces (SELF_SIGNED_CERT_IN_CHAIN,
// then a missing-secret error) reads like a credential problem rather than a
// missing file.
//
// The SQL Editor needs no connection string, no certificate and no secret, so it
// is the way to get a schema onto a database when the connection route is not
// available. This produces the script to paste into it.
//
// Generated, never hand-edited, and deliberately not committed: a second copy of
// the schema in the repository is a copy that can drift from drizzle/, and the
// schema of record has to stay the migrations. `pnpm db:sql` regenerates it.
//
//   pnpm db:sql                      # writes database/schema-apply.sql
//   open database/schema-apply.sql   # select all, paste into the SQL Editor
//
// Reads the journal rather than globbing the directory, so the order is the
// order migrations are meant to be applied in rather than alphabetical.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const drizzleDir = join(root, "drizzle");
const outFile = join(root, "database", "schema-apply.sql");

/**
 * The `-->` markers are drizzle-kit's statement separators, and only mean
 * something to its own migrator. Left in place they are SQL comments, so they
 * would not break anything — but the SQL Editor would echo them as part of the
 * script the operator reads before running it, which is noise on the one screen
 * where a human is deciding whether to execute the thing.
 */
function stripBreakpoints(sql: string): string {
  return sql.replace(/--> statement-breakpoint\s*/g, "");
}

async function main() {
  const journal = JSON.parse(
    await readFile(join(drizzleDir, "meta", "_journal.json"), "utf8")
  ) as { entries: { idx: number; tag: string }[] };

  const ordered = [...journal.entries].sort((a, b) => a.idx - b.idx);
  if (!ordered.length) throw new Error("The journal lists no migrations.");

  const sections: string[] = [];
  for (const entry of ordered) {
    const path = join(drizzleDir, `${entry.tag}.sql`);
    const sql = await readFile(path, "utf8");
    sections.push(
      [
        `-- ${"=".repeat(74)}`,
        `-- Migration ${entry.idx}: ${entry.tag}`,
        `-- ${"=".repeat(74)}`,
        "",
        stripBreakpoints(sql).trim(),
      ].join("\n")
    );
  }

  // The same assertions scripts/verify-schema.ts makes, as queries a human can
  // paste and read. db:verify is the real check and needs a connection; this is
  // what is available when there is not one, and it is deliberately the same
  // questions rather than a looser approximation.
  const verify = `-- ${"=".repeat(74)}
-- Verify. Expect five rows, all "t", and a final row of 0.
-- ${"=".repeat(74)}
SELECT c.relname AS table, c.relrowsecurity AS rls_enabled
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
 WHERE n.nspname = 'public' AND c.relkind = 'r'
 ORDER BY c.relname;

SELECT count(*) AS policies_should_be_zero
  FROM pg_policies WHERE schemaname = 'public';

SELECT
  EXISTS (SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'public' AND table_name = 'users'
             AND column_name = 'authUserId')          AS has_authuserid,
  EXISTS (SELECT 1 FROM information_schema.columns
           WHERE table_schema = 'public' AND table_name = 'users'
             AND column_name = 'passwordHash')        AS has_passwordhash_must_be_false;`;

  const header = `-- TSC Case Management — full schema for the Supabase SQL Editor.
--
-- GENERATED by pnpm db:sql from drizzle/. Do not edit: regenerate instead.
--
-- Apply in order in the Supabase SQL Editor (SQL Editor -> New query -> paste ->
-- Run). This is the fallback for when a verified connection is not available —
-- it needs no connection string, no CA certificate and no service key, which is
-- also its weakness: nothing here verifies which database it landed in, and
-- nothing records that it ran. Run the verification queries at the end and read
-- them.
--
-- The CI path (.github/workflows/db-push.yml) is preferred where it works,
-- because it records what it applied in drizzle.__drizzle_migrations and this
-- does not. A database set up this way has no migration history, so drizzle-kit
-- will try to re-apply everything; that is harmless (every statement here is
-- guarded or will simply fail on "already exists"), but expect it.`;

  await writeFile(
    outFile,
    `${header}\n\n${sections.join("\n\n")}\n\n${verify}\n`,
    "utf8"
  );

  const sql = await readFile(outFile, "utf8");
  console.log(
    `[db:sql] ${ordered.length} migrations -> database/schema-apply.sql (${sql.split("\n").length} lines)`
  );
  for (const entry of ordered)
    console.log(`[db:sql]   ${entry.idx} ${entry.tag}`);
  console.log("[db:sql] Verification queries are appended at the end.");
}

main().catch((error: unknown) => {
  console.error("[db:sql] Could not build the schema script:", error);
  process.exit(1);
});
